### ISSUE TITLE
Control de campos editar productos

### ISSUE THREAD

**Issue by fabriziotonin** [karo18delgado/Proyecto-Final-RollingCode#6]
Al editar los productos poner un max length para evitar la carga de contenido no deseado. 
![image](https://user-images.githubusercontent.com/51201108/127562463-590ea931-4181-4a93-8bc6-e6f823b203b8.png)

**Comment by agustingu20** [comment]
Buenas tardes, ya se puso un max length en el modal editar para evitar la carga de contenido no deseado. Además se agregó las validaciones para que el precio no pueda ser negativo, y solamente puedan ingresarse números.
![Correcciones final](https://user-images.githubusercontent.com/76539028/127754676-2ed31255-dfca-41b6-ab6f-9d13c01e8f34.jpg)
